"""add_story_analysis

Revision ID: 077a8d9f9d9b
Revises: cf3d8e3125cf
Create Date: 2026-10-02 19:38:40.122312

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "077a8d9f9d9b"
down_revision: str | Sequence[str] | None = "cf3d8e3125cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_analysis_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("story_id", sa.String(length=36), nullable=False),
        sa.Column("story_version_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["story_id"], ["stories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["story_version_id"], ["story_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_analysis_results_story_id"),
        "story_analysis_results",
        ["story_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_story_analysis_results_story_version_id"),
        "story_analysis_results",
        ["story_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_story_analysis_results_story_version_id"), table_name="story_analysis_results"
    )
    op.drop_index(op.f("ix_story_analysis_results_story_id"), table_name="story_analysis_results")
    op.drop_table("story_analysis_results")
    # ### end Alembic commands ###
