"""add_asset_domain

Revision ID: 0c45d3685f5a
Revises: 2ac946d09256
Create Date: 2026-10-02 20:36:25.826397

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c45d3685f5a"
down_revision: str | Sequence[str] | None = "2ac946d09256"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("storage_backend", sa.String(length=50), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("asset_metadata", sa.JSON(), nullable=True),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_series_id"), "assets", ["series_id"], unique=False)
    op.create_index("ix_assets_series_id_type", "assets", ["series_id", "asset_type"], unique=False)
    op.create_index(op.f("ix_assets_shot_id"), "assets", ["shot_id"], unique=False)
    op.create_table(
        "asset_characters",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id", "character_id"),
    )
    op.create_table(
        "asset_locations",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("location_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id", "location_id"),
    )
    op.create_table(
        "asset_objects",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["object_id"], ["story_objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id", "object_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("asset_objects")
    op.drop_table("asset_locations")
    op.drop_table("asset_characters")
    op.drop_index(op.f("ix_assets_shot_id"), table_name="assets")
    op.drop_index("ix_assets_series_id_type", table_name="assets")
    op.drop_index(op.f("ix_assets_series_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
