"""add_video_assembly_domain

Revision ID: 1a397087b676
Revises: 76eb2b8e9b53
Create Date: 2026-10-02 22:55:01.854628

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a397087b676"
down_revision: str | Sequence[str] | None = "76eb2b8e9b53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_assemblies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("output_config", sa.JSON(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("assembly_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_video_assemblies_episode_id"), "video_assemblies", ["episode_id"], unique=True
    )
    op.create_index(
        op.f("ix_video_assemblies_series_id"), "video_assemblies", ["series_id"], unique=False
    )
    op.create_index(
        op.f("ix_video_assemblies_status"), "video_assemblies", ["status"], unique=False
    )
    op.create_table(
        "assembly_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("assembly_id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=True),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("track", sa.String(length=20), nullable=False),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.Column("start_time_seconds", sa.Float(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=True),
        sa.Column("narration_id", sa.String(length=36), nullable=True),
        sa.Column("audio_cue_id", sa.String(length=36), nullable=True),
        sa.Column("item_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assembly_id"], ["video_assemblies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["audio_cue_id"], ["audio_cues.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["narration_id"], ["narrations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assembly_id", "sequence_order"),
    )
    op.create_index(
        op.f("ix_assembly_items_assembly_id"), "assembly_items", ["assembly_id"], unique=False
    )
    op.create_index(
        op.f("ix_assembly_items_asset_id"), "assembly_items", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_assembly_items_audio_cue_id"), "assembly_items", ["audio_cue_id"], unique=False
    )
    op.create_index(
        op.f("ix_assembly_items_episode_id"), "assembly_items", ["episode_id"], unique=False
    )
    op.create_index(
        op.f("ix_assembly_items_narration_id"), "assembly_items", ["narration_id"], unique=False
    )
    op.create_index(
        op.f("ix_assembly_items_scene_id"), "assembly_items", ["scene_id"], unique=False
    )
    op.create_index(
        op.f("ix_assembly_items_series_id"), "assembly_items", ["series_id"], unique=False
    )
    op.create_index(op.f("ix_assembly_items_shot_id"), "assembly_items", ["shot_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assembly_items_shot_id"), table_name="assembly_items")
    op.drop_index(op.f("ix_assembly_items_series_id"), table_name="assembly_items")
    op.drop_index(op.f("ix_assembly_items_scene_id"), table_name="assembly_items")
    op.drop_index(op.f("ix_assembly_items_narration_id"), table_name="assembly_items")
    op.drop_index(op.f("ix_assembly_items_episode_id"), table_name="assembly_items")
    op.drop_index(op.f("ix_assembly_items_audio_cue_id"), table_name="assembly_items")
    op.drop_index(op.f("ix_assembly_items_asset_id"), table_name="assembly_items")
    op.drop_index(op.f("ix_assembly_items_assembly_id"), table_name="assembly_items")
    op.drop_table("assembly_items")
    op.drop_index(op.f("ix_video_assemblies_status"), table_name="video_assemblies")
    op.drop_index(op.f("ix_video_assemblies_series_id"), table_name="video_assemblies")
    op.drop_index(op.f("ix_video_assemblies_episode_id"), table_name="video_assemblies")
    op.drop_table("video_assemblies")
    # ### end Alembic commands ###
