"""add_shot_specifications

Revision ID: 2ac946d09256
Revises: 077a8d9f9d9b
Create Date: 2026-10-02 20:17:41.032104

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ac946d09256"
down_revision: str | Sequence[str] | None = "077a8d9f9d9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shot_specifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=False),
        sa.Column("intent", sa.Text(), nullable=True),
        sa.Column("framing", sa.Text(), nullable=True),
        sa.Column("composition", sa.Text(), nullable=True),
        sa.Column("camera_notes", sa.Text(), nullable=True),
        sa.Column("camera_movement", sa.Text(), nullable=True),
        sa.Column("subject_notes", sa.Text(), nullable=True),
        sa.Column("visual_direction", sa.Text(), nullable=True),
        sa.Column("aspect_ratio", sa.String(length=20), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("character_refs", sa.JSON(), nullable=True),
        sa.Column("location_refs", sa.JSON(), nullable=True),
        sa.Column("object_refs", sa.JSON(), nullable=True),
        sa.Column("output_constraints", sa.JSON(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shot_id"),
    )
    op.create_index(
        op.f("ix_shot_specifications_shot_id"),
        "shot_specifications",
        ["shot_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shot_specifications_shot_id"), table_name="shot_specifications")
    op.drop_table("shot_specifications")
    # ### end Alembic commands ###
