"""add_caption_domain

Revision ID: 2b320a989326
Revises: 1a397087b676
Create Date: 2026-10-02 23:09:02.525367

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b320a989326"
down_revision: str | Sequence[str] | None = "1a397087b676"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "captions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("assembly_id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=True),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("narration_id", sa.String(length=36), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_time_seconds", sa.Float(), nullable=False),
        sa.Column("end_time_seconds", sa.Float(), nullable=False),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.Column("style", sa.JSON(), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.Column("caption_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assembly_id"], ["video_assemblies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["narration_id"], ["narrations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_captions_assembly_id", "captions", ["assembly_id"], unique=False)
    op.create_index("ix_captions_episode_id", "captions", ["episode_id"], unique=False)
    op.create_index("ix_captions_narration_id", "captions", ["narration_id"], unique=False)
    op.create_index("ix_captions_series_id", "captions", ["series_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_captions_series_id", table_name="captions")
    op.drop_index("ix_captions_narration_id", table_name="captions")
    op.drop_index("ix_captions_episode_id", table_name="captions")
    op.drop_index("ix_captions_assembly_id", table_name="captions")
    op.drop_table("captions")
    # ### end Alembic commands ###
