"""add_universe_engine

Revision ID: 494938a37860
Revises: cfb72ab681f7
Create Date: 2026-10-02 19:27:34.321818

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "494938a37860"
down_revision: str | Sequence[str] | None = "cfb72ab681f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_bibles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("voice_style", sa.Text(), nullable=True),
        sa.Column("narration_style", sa.Text(), nullable=True),
        sa.Column("dialogue_style", sa.Text(), nullable=True),
        sa.Column("music_style", sa.Text(), nullable=True),
        sa.Column("sound_effect_style", sa.Text(), nullable=True),
        sa.Column("ambient_style", sa.Text(), nullable=True),
        sa.Column("audio_notes", sa.Text(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id"),
    )
    op.create_index(op.f("ix_audio_bibles_series_id"), "audio_bibles", ["series_id"], unique=False)
    op.create_table(
        "visual_bibles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("art_style", sa.Text(), nullable=True),
        sa.Column("color_palette", sa.Text(), nullable=True),
        sa.Column("lighting_style", sa.Text(), nullable=True),
        sa.Column("camera_style", sa.Text(), nullable=True),
        sa.Column("lens_style", sa.Text(), nullable=True),
        sa.Column("composition_style", sa.Text(), nullable=True),
        sa.Column("environment_style", sa.Text(), nullable=True),
        sa.Column("character_rendering_style", sa.Text(), nullable=True),
        sa.Column("aspect_ratio", sa.String(length=20), nullable=True),
        sa.Column("visual_notes", sa.Text(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id"),
    )
    op.create_index(
        op.f("ix_visual_bibles_series_id"), "visual_bibles", ["series_id"], unique=False
    )
    op.add_column("characters", sa.Column("voice_reference", sa.Text(), nullable=True))
    op.add_column("characters", sa.Column("extra", sa.JSON(), nullable=True))
    op.add_column("locations", sa.Column("atmosphere", sa.Text(), nullable=True))
    op.add_column("locations", sa.Column("visual_characteristics", sa.Text(), nullable=True))
    op.add_column("locations", sa.Column("extra", sa.JSON(), nullable=True))
    op.add_column("story_objects", sa.Column("significance", sa.Text(), nullable=True))
    op.add_column("story_objects", sa.Column("extra", sa.JSON(), nullable=True))
    op.add_column("worlds", sa.Column("current_era", sa.String(length=255), nullable=True))
    op.add_column("worlds", sa.Column("history_context", sa.Text(), nullable=True))
    op.add_column("worlds", sa.Column("social_structure", sa.Text(), nullable=True))
    op.add_column("worlds", sa.Column("timeline_notes", sa.Text(), nullable=True))
    op.add_column("worlds", sa.Column("extra", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worlds", "extra")
    op.drop_column("worlds", "timeline_notes")
    op.drop_column("worlds", "social_structure")
    op.drop_column("worlds", "history_context")
    op.drop_column("worlds", "current_era")
    op.drop_column("story_objects", "extra")
    op.drop_column("story_objects", "significance")
    op.drop_column("locations", "extra")
    op.drop_column("locations", "visual_characteristics")
    op.drop_column("locations", "atmosphere")
    op.drop_column("characters", "extra")
    op.drop_column("characters", "voice_reference")
    op.drop_index(op.f("ix_visual_bibles_series_id"), table_name="visual_bibles")
    op.drop_table("visual_bibles")
    op.drop_index(op.f("ix_audio_bibles_series_id"), table_name="audio_bibles")
    op.drop_table("audio_bibles")
    # ### end Alembic commands ###
