"""add_voice_and_narration_domain

Revision ID: 53d3cf4dea2d
Revises: 5cc3a5a2191a
Create Date: 2026-10-02 22:32:51.598187

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53d3cf4dea2d"
down_revision: str | Sequence[str] | None = "5cc3a5a2191a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("character_id", sa.String(length=36), nullable=True),
        sa.Column("voice_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "name"),
    )
    op.create_index(op.f("ix_voices_character_id"), "voices", ["character_id"], unique=False)
    op.create_index(op.f("ix_voices_series_id"), "voices", ["series_id"], unique=False)
    op.create_table(
        "narrations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=True),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("voice_id", sa.String(length=36), nullable=True),
        sa.Column("character_id", sa.String(length=36), nullable=True),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("narration_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("generated_asset_id", sa.String(length=36), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("audio_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["generated_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["voice_id"], ["voices.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_narrations_character_id"), "narrations", ["character_id"], unique=False
    )
    op.create_index(op.f("ix_narrations_episode_id"), "narrations", ["episode_id"], unique=False)
    op.create_index(
        op.f("ix_narrations_generated_asset_id"), "narrations", ["generated_asset_id"], unique=False
    )
    op.create_index(op.f("ix_narrations_scene_id"), "narrations", ["scene_id"], unique=False)
    op.create_index(op.f("ix_narrations_series_id"), "narrations", ["series_id"], unique=False)
    op.create_index(op.f("ix_narrations_shot_id"), "narrations", ["shot_id"], unique=False)
    op.create_index(op.f("ix_narrations_voice_id"), "narrations", ["voice_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_narrations_voice_id"), table_name="narrations")
    op.drop_index(op.f("ix_narrations_shot_id"), table_name="narrations")
    op.drop_index(op.f("ix_narrations_series_id"), table_name="narrations")
    op.drop_index(op.f("ix_narrations_scene_id"), table_name="narrations")
    op.drop_index(op.f("ix_narrations_generated_asset_id"), table_name="narrations")
    op.drop_index(op.f("ix_narrations_episode_id"), table_name="narrations")
    op.drop_index(op.f("ix_narrations_character_id"), table_name="narrations")
    op.drop_table("narrations")
    op.drop_index(op.f("ix_voices_series_id"), table_name="voices")
    op.drop_index(op.f("ix_voices_character_id"), table_name="voices")
    op.drop_table("voices")
    # ### end Alembic commands ###
