"""add_video_generation_jobs

Revision ID: 5cc3a5a2191a
Revises: 760f35d11b4a
Create Date: 2026-10-02 21:03:28.720072

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cc3a5a2191a"
down_revision: str | Sequence[str] | None = "760f35d11b4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_generation_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("source_asset_id", sa.String(length=36), nullable=True),
        sa.Column("request_payload", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("result_metadata", sa.JSON(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_video_generation_jobs_series_id"),
        "video_generation_jobs",
        ["series_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_video_generation_jobs_shot_id"), "video_generation_jobs", ["shot_id"], unique=False
    )
    op.create_index(
        op.f("ix_video_generation_jobs_source_asset_id"),
        "video_generation_jobs",
        ["source_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_video_generation_jobs_status"), "video_generation_jobs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_generation_jobs_status"), table_name="video_generation_jobs")
    op.drop_index(
        op.f("ix_video_generation_jobs_source_asset_id"), table_name="video_generation_jobs"
    )
    op.drop_index(op.f("ix_video_generation_jobs_shot_id"), table_name="video_generation_jobs")
    op.drop_index(op.f("ix_video_generation_jobs_series_id"), table_name="video_generation_jobs")
    op.drop_table("video_generation_jobs")
    # ### end Alembic commands ###
