"""add_image_generation_jobs

Revision ID: 760f35d11b4a
Revises: 0c45d3685f5a
Create Date: 2026-10-02 20:53:40.432107

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "760f35d11b4a"
down_revision: str | Sequence[str] | None = "0c45d3685f5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_generation_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("request_payload", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approval_status", sa.String(length=20), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("result_asset_ids", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_image_generation_jobs_series_id"),
        "image_generation_jobs",
        ["series_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_image_generation_jobs_shot_id"), "image_generation_jobs", ["shot_id"], unique=False
    )
    op.create_index(
        op.f("ix_image_generation_jobs_status"), "image_generation_jobs", ["status"], unique=False
    )
    op.add_column("assets", sa.Column("approval_status", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "approval_status")
    op.drop_index(op.f("ix_image_generation_jobs_status"), table_name="image_generation_jobs")
    op.drop_index(op.f("ix_image_generation_jobs_shot_id"), table_name="image_generation_jobs")
    op.drop_index(op.f("ix_image_generation_jobs_series_id"), table_name="image_generation_jobs")
    op.drop_table("image_generation_jobs")
    # ### end Alembic commands ###
