"""add_audio_cue_domain

Revision ID: 76eb2b8e9b53
Revises: 53d3cf4dea2d
Create Date: 2026-10-02 22:49:46.523920

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76eb2b8e9b53"
down_revision: str | Sequence[str] | None = "53d3cf4dea2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_cues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=True),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("audio_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("start_time_seconds", sa.Float(), nullable=True),
        sa.Column("end_time_seconds", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("loop", sa.Boolean(), nullable=False),
        sa.Column("fade_in", sa.Boolean(), nullable=False),
        sa.Column("fade_out", sa.Boolean(), nullable=False),
        sa.Column("generated_asset_id", sa.String(length=36), nullable=True),
        sa.Column("audio_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["generated_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "name"),
    )
    op.create_index(op.f("ix_audio_cues_episode_id"), "audio_cues", ["episode_id"], unique=False)
    op.create_index(
        op.f("ix_audio_cues_generated_asset_id"), "audio_cues", ["generated_asset_id"], unique=False
    )
    op.create_index(op.f("ix_audio_cues_scene_id"), "audio_cues", ["scene_id"], unique=False)
    op.create_index(op.f("ix_audio_cues_series_id"), "audio_cues", ["series_id"], unique=False)
    op.create_index(
        "ix_audio_cues_series_id_type", "audio_cues", ["series_id", "audio_type"], unique=False
    )
    op.create_index(op.f("ix_audio_cues_shot_id"), "audio_cues", ["shot_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audio_cues_shot_id"), table_name="audio_cues")
    op.drop_index("ix_audio_cues_series_id_type", table_name="audio_cues")
    op.drop_index(op.f("ix_audio_cues_series_id"), table_name="audio_cues")
    op.drop_index(op.f("ix_audio_cues_scene_id"), table_name="audio_cues")
    op.drop_index(op.f("ix_audio_cues_generated_asset_id"), table_name="audio_cues")
    op.drop_index(op.f("ix_audio_cues_episode_id"), table_name="audio_cues")
    op.drop_table("audio_cues")
    # ### end Alembic commands ###
