"""Add generation_costs

Revision ID: 7b329de0d3c9
Revises: f85966cf28d3
Create Date: 2026-10-03 01:23:58.024221

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b329de0d3c9"
down_revision: str | Sequence[str] | None = "f85966cf28d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_costs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=True),
        sa.Column("generation_type", sa.String(length=20), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("asset_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("cost_status", sa.String(length=20), nullable=False),
        sa.Column("cost_currency", sa.String(length=3), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=19, scale=6), nullable=False),
        sa.Column("usage_components", sa.JSON(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "correlation_id"),
    )
    op.create_index(
        op.f("ix_generation_costs_asset_id"), "generation_costs", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_generation_costs_episode_id"), "generation_costs", ["episode_id"], unique=False
    )
    op.create_index(
        op.f("ix_generation_costs_generation_type"),
        "generation_costs",
        ["generation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_costs_job_id"), "generation_costs", ["job_id"], unique=False
    )
    op.create_index(op.f("ix_generation_costs_model"), "generation_costs", ["model"], unique=False)
    op.create_index(
        op.f("ix_generation_costs_provider"), "generation_costs", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_generation_costs_recorded_at"), "generation_costs", ["recorded_at"], unique=False
    )
    op.create_index(
        op.f("ix_generation_costs_series_id"), "generation_costs", ["series_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generation_costs_series_id"), table_name="generation_costs")
    op.drop_index(op.f("ix_generation_costs_recorded_at"), table_name="generation_costs")
    op.drop_index(op.f("ix_generation_costs_provider"), table_name="generation_costs")
    op.drop_index(op.f("ix_generation_costs_model"), table_name="generation_costs")
    op.drop_index(op.f("ix_generation_costs_job_id"), table_name="generation_costs")
    op.drop_index(op.f("ix_generation_costs_generation_type"), table_name="generation_costs")
    op.drop_index(op.f("ix_generation_costs_episode_id"), table_name="generation_costs")
    op.drop_index(op.f("ix_generation_costs_asset_id"), table_name="generation_costs")
    op.drop_table("generation_costs")
    # ### end Alembic commands ###
