"""add_qa_issue_resolution

Revision ID: bf64256c5718
Revises: d1346a145770
Create Date: 2026-10-03 01:50:48.115052

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf64256c5718"
down_revision: str | Sequence[str] | None = "d1346a145770"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qa_issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=True),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("asset_id", sa.String(length=36), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolution_type", sa.String(length=30), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("regenerated_asset_id", sa.String(length=36), nullable=True),
        sa.Column("qa_finding_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["regenerated_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_qa_issues_series_episode", "qa_issues", ["series_id", "episode_id"], unique=False
    )
    op.create_index(op.f("ix_qa_issues_series_id"), "qa_issues", ["series_id"], unique=False)
    op.create_index("ix_qa_issues_series_shot", "qa_issues", ["series_id", "shot_id"], unique=False)
    op.create_index("ix_qa_issues_status", "qa_issues", ["status"], unique=False)
    op.create_table(
        "qa_resolution_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("action_type", sa.String(length=30), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("generated_asset_id", sa.String(length=36), nullable=True),
        sa.Column("generated_job_id", sa.String(length=50), nullable=True),
        sa.Column("action_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["generated_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["issue_id"], ["qa_issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_qa_resolution_actions_issue", "qa_resolution_actions", ["issue_id"], unique=False
    )
    op.create_index(
        "ix_qa_resolution_actions_status", "qa_resolution_actions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_qa_resolution_actions_status", table_name="qa_resolution_actions")
    op.drop_index("ix_qa_resolution_actions_issue", table_name="qa_resolution_actions")
    op.drop_table("qa_resolution_actions")
    op.drop_index("ix_qa_issues_status", table_name="qa_issues")
    op.drop_index("ix_qa_issues_series_shot", table_name="qa_issues")
    op.drop_index(op.f("ix_qa_issues_series_id"), table_name="qa_issues")
    op.drop_index("ix_qa_issues_series_episode", table_name="qa_issues")
    op.drop_table("qa_issues")
    # ### end Alembic commands ###
