"""add_story_domain

Revision ID: cf3d8e3125cf
Revises: 494938a37860
Create Date: 2026-10-02 19:32:45.483745

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf3d8e3125cf"
down_revision: str | Sequence[str] | None = "494938a37860"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_content", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stories_series_id"), "stories", ["series_id"], unique=False)
    op.create_table(
        "story_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("story_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["story_id"], ["stories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_id", "version_number"),
    )
    op.create_index(
        op.f("ix_story_versions_story_id"), "story_versions", ["story_id"], unique=False
    )
    with op.batch_alter_table("episodes", recreate="always") as batch_op:
        batch_op.add_column(sa.Column("story_id", sa.String(length=36), nullable=True))
        batch_op.create_index("ix_episodes_story_id", ["story_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_episodes_story_id", "stories", ["story_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("episodes", recreate="always") as batch_op:
        batch_op.drop_constraint("fk_episodes_story_id", type_="foreignkey")
        batch_op.drop_index("ix_episodes_story_id")
        batch_op.drop_column("story_id")
    op.drop_index(op.f("ix_story_versions_story_id"), table_name="story_versions")
    op.drop_table("story_versions")
    op.drop_index(op.f("ix_stories_series_id"), table_name="stories")
    op.drop_table("stories")
    # ### end Alembic commands ###
