"""Add episode budgets and reservations

Revision ID: d1346a145770
Revises: 7b329de0d3c9
Create Date: 2026-10-03 01:29:40.169234

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1346a145770"
down_revision: str | Sequence[str] | None = "7b329de0d3c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_reservations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("generation_type", sa.String(length=20), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=19, scale=6), nullable=False),
        sa.Column("actual_cost", sa.Numeric(precision=19, scale=6), nullable=True),
        sa.Column("cost_currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "correlation_id"),
    )
    op.create_index(
        op.f("ix_budget_reservations_episode_id"),
        "budget_reservations",
        ["episode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_budget_reservations_generation_type"),
        "budget_reservations",
        ["generation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_budget_reservations_job_id"), "budget_reservations", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_reservations_series_id"), "budget_reservations", ["series_id"], unique=False
    )
    op.create_table(
        "episode_budgets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("budget_amount", sa.Numeric(precision=19, scale=6), nullable=False),
        sa.Column("cost_currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("usage_limits", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "episode_id"),
    )
    op.create_index(
        op.f("ix_episode_budgets_episode_id"), "episode_budgets", ["episode_id"], unique=False
    )
    op.create_index(
        op.f("ix_episode_budgets_series_id"), "episode_budgets", ["series_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_episode_budgets_series_id"), table_name="episode_budgets")
    op.drop_index(op.f("ix_episode_budgets_episode_id"), table_name="episode_budgets")
    op.drop_table("episode_budgets")
    op.drop_index(op.f("ix_budget_reservations_series_id"), table_name="budget_reservations")
    op.drop_index(op.f("ix_budget_reservations_job_id"), table_name="budget_reservations")
    op.drop_index(op.f("ix_budget_reservations_generation_type"), table_name="budget_reservations")
    op.drop_index(op.f("ix_budget_reservations_episode_id"), table_name="budget_reservations")
    op.drop_table("budget_reservations")
    # ### end Alembic commands ###
