"""Add publishing_jobs

Revision ID: f85966cf28d3
Revises: f651f303d9cf
Create Date: 2026-10-03 01:14:41.938188

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f85966cf28d3"
down_revision: str | Sequence[str] | None = "f651f303d9cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publishing_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("thumbnail_asset_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_snapshot", sa.JSON(), nullable=True),
        sa.Column("provider_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_publication_id", sa.String(length=255), nullable=True),
        sa.Column("external_url", sa.String(length=1024), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thumbnail_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_publishing_jobs_asset_id"), "publishing_jobs", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_publishing_jobs_correlation_id"),
        "publishing_jobs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publishing_jobs_episode_id"), "publishing_jobs", ["episode_id"], unique=False
    )
    op.create_index(
        "ix_publishing_jobs_idempotency_key", "publishing_jobs", ["idempotency_key"], unique=False
    )
    op.create_index(
        "ix_publishing_jobs_scheduled_at", "publishing_jobs", ["scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_publishing_jobs_series_id"), "publishing_jobs", ["series_id"], unique=False
    )
    op.create_index("ix_publishing_jobs_status", "publishing_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_publishing_jobs_thumbnail_asset_id"),
        "publishing_jobs",
        ["thumbnail_asset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publishing_jobs_thumbnail_asset_id"), table_name="publishing_jobs")
    op.drop_index("ix_publishing_jobs_status", table_name="publishing_jobs")
    op.drop_index(op.f("ix_publishing_jobs_series_id"), table_name="publishing_jobs")
    op.drop_index("ix_publishing_jobs_scheduled_at", table_name="publishing_jobs")
    op.drop_index("ix_publishing_jobs_idempotency_key", table_name="publishing_jobs")
    op.drop_index(op.f("ix_publishing_jobs_episode_id"), table_name="publishing_jobs")
    op.drop_index(op.f("ix_publishing_jobs_correlation_id"), table_name="publishing_jobs")
    op.drop_index(op.f("ix_publishing_jobs_asset_id"), table_name="publishing_jobs")
    op.drop_table("publishing_jobs")
    # ### end Alembic commands ###
